/* eslint-disable import/prefer-default-export */
import gqlService from '@modules/vendorbulktools/services/graphql';
import BaseProductUpload from '@modules/vendorbulktools/pages/default/components/baseProductUpload';

export const bulkToolsOptions = [
    {
        name: 'Product Master Upload',
        code: 'product_upload_master',
        acl: 'oms_lite_vendor_product_upload_master',
        sample: 'vendor_product',
        activity: null,
        gqlUpload: gqlService.vendorProductMasterUpload,
        component: <BaseProductUpload />,
    },
    {
        name: 'Product Configurable Upload',
        code: 'product_upload_configurable',
        acl: 'vendor_manage_product_upload',
        sample: 'vendor_product_configurable',
        activity: null,
        gqlUpload: gqlService.vendorProductConfigurableUpload,
        component: <BaseProductUpload />,
    },
    {
        name: 'Product Bundle Upload',
        code: 'product_upload_bundle',
        acl: 'vendor_manage_product_upload',
        sample: 'vendor_product_bundle',
        activity: null,
        gqlUpload: gqlService.vendorProductBundleUpload,
        component: <BaseProductUpload />,
    },
    {
        name: 'Product Grouped Upload',
        code: 'product_upload_grouped',
        acl: 'vendor_manage_product_upload',
        sample: 'vendor_product_grouped',
        activity: null,
        gqlUpload: gqlService.vendorProductGroupedUpload,
        component: <BaseProductUpload />,
    },
    {
        name: 'Product Price Upload',
        code: 'product_upload_price',
        acl: 'vendor_manage_product_upload',
        sample: 'vendor_product_price',
        activity: null,
        gqlUpload: gqlService.vendorProductPriceUpload,
        component: <BaseProductUpload />,
    },
    {
        name: 'Product Price by Location Upload',
        code: 'product_upload_price_by_location',
        acl: 'vendor_manage_product_upload',
        sample: 'vendor_product_price_location',
        activity: null,
        gqlUpload: gqlService.vendorProductPriceLocationUpload,
        component: <BaseProductUpload />,
    },
    {
        name: 'Product Image Upload',
        code: 'product_image_upload',
        acl: 'vendor_manage_product_upload',
        sample: 'vendor_product_image',
        activity: null,
        gqlUpload: gqlService.vendorProductImageUpload,
        component: <BaseProductUpload />,
    },
    {
        name: 'Product Simplify Upload',
        code: 'product_simplify_upload',
        acl: 'vendor_manage_product_upload',
        sample: 'vendor_product_simplify',
        activity: null,
        gqlUpload: gqlService.vendorProductSimplifyUpload,
        component: <BaseProductUpload />,
    },
    {
        name: 'Assign Product Category Upload',
        code: 'assign_product_category_upload',
        acl: 'vendor_manage_product_upload',
        sample: 'vendor_category_assignation',
        activity: null,
        gqlUpload: gqlService.vendorCategoryAssignationUpload,
        component: <BaseProductUpload />,
    },
    {
        name: 'Product Stock Upload',
        code: 'vendor_stock_upload',
        acl: 'vendor_manage_product_upload',
        sample: gqlService.getVendorStockUploadSampleCsv,
        activity: null,
        gqlUpload: gqlService.vendorProductStockUpload,
        component: <BaseProductUpload />,
        is_no_tutorial: true,
    },
];
