version: '3'
services:
    frontend:
        build:
            context: ./
        environment:
            - PORT=3000
            - NODE_ENV=production
            - APP_ENV=prod
        ports:
            - 3000:3000