env:
  DOCKER_HOST: tcp://dockerdind:2375
steps:
  
  - block: "Request build docker image"

  - label: ":docker: build docker"
    command:
      - "sh .buildkite/build.sh oms-demo-pwa"
    agents:
      - "icube-staging=true"
    
  - block: "deploy staging"

  - label: "Release to staging"
    command:
      - "sh .buildkite/deploy.sh iii-nonprod oms-demo-pwa"
    agents:
      - "icube-staging=true"
  
  - block: "Release to production"

  - label: ":rocket: Deploy iii-prod"
    command:
      - "sh .buildkite/deploy.sh iii-prod oms-demo-pwa"
    agents:
      - "iii-prod=true"
